import {
  AEO_BULLETS,
  FAQ_ITEMS,
  ORGANIZATION,
  PROGRAM_PILLARS,
  SITE_NAME,
  SITE_TAGLINE,
  SITE_URL,
} from "@/lib/seo";
import { LAUNCH_DATE_LABEL, launchFeatures } from "@/lib/launch";
import { GUIDES } from "@/lib/guides";
import { PILLARS } from "@/lib/pillars";
import { POSTS } from "@/lib/posts";
import { AUTHOR } from "@/lib/author";

export async function GET() {
  const lines = [
    `# ${SITE_NAME}`,
    "",
    `> ${SITE_TAGLINE}`,
    "",
    "## Canonical URL",
    SITE_URL,
    "",
    "## Launch date",
    LAUNCH_DATE_LABEL,
    "",
    "## What is Reborn Academy?",
    FAQ_ITEMS.find((f) => f.id === "what-is-reborn-academy")?.answer ?? "",
    "",
    "## Founders",
    ...ORGANIZATION.founders.map((f) => `- ${f.name} (${f.role}): ${f.description}`),
    "",
    "## Launch features",
    ...launchFeatures.map((f) => `- ${f.title}: ${f.desc}`),
    "",
    "## Topics & Programs",
    ...PROGRAM_PILLARS.map((p) => `- ${p.name} — ${p.description}`),
    "",
    "## Key facts",
    ...AEO_BULLETS.map((b) => `- ${b}`),
    "",
    "## Pages",
    `- Home: ${SITE_URL}/`,
    `- What is Reborn Academy: ${SITE_URL}/what-is-reborn-academy`,
    `- Programs: ${SITE_URL}/programs`,
    ...PILLARS.map((p) => `- ${p.name} pillar: ${SITE_URL}/programs/${p.slug}`),
    `- Journal by ${AUTHOR.name} (${AUTHOR.url}): ${SITE_URL}/blog`,
    ...POSTS.map((post) => `- ${post.title}: ${SITE_URL}/blog/${post.slug}`),
    `- Guides: ${SITE_URL}/guides`,
    ...GUIDES.map((g) => `- ${g.title}: ${SITE_URL}/guides/${g.slug}`),
    `- Launch: ${SITE_URL}/launch`,
    `- About: ${SITE_URL}/about`,
    `- FAQ: ${SITE_URL}/faq`,
    `- Waitlist: ${SITE_URL}/waitlist`,
    `- RSS: ${SITE_URL}/feed.xml`,
    "",
    "## How to join",
    `Join the free waitlist at ${SITE_URL}/waitlist before the ${LAUNCH_DATE_LABEL} re-launch.`,
    "",
    "## Premium tier",
    "RB Insiders — premium membership with deeper access (details at launch).",
    "",
    "## Parent organization",
    `Thy Kingdom Network — ${ORGANIZATION.parentOrganization.url}`,
    "",
    "## Related",
    "- I AM REBORN: https://iamreborn.net",
    "- Daniel Ziedins: https://danielziedins.com",
    "",
    "## FAQ",
    ...FAQ_ITEMS.map((f) => `### ${f.question}\n${f.answer}`),
    "",
    "## AI / machine-readable",
    `- ai.txt: ${SITE_URL}/ai.txt`,
    `- geo.txt: ${SITE_URL}/geo.txt`,
    `- Full documentation: ${SITE_URL}/llms-full.txt`,
  ];

  return new Response(lines.join("\n"), {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=86400",
    },
  });
}
