import {
  AEO_BULLETS,
  AEO_DEFINITION,
  FAQ_ITEMS,
  INTRO_VIDEO,
  ORGANIZATION,
  PROGRAM_PILLARS,
  SITE_DESCRIPTION,
  SITE_KEYWORDS,
  SITE_NAME,
  SITE_TAGLINE,
  SITE_URL,
} from "@/lib/seo";
import { LAUNCH_DATE_LABEL, launchFeatures } from "@/lib/launch";

export async function GET() {
  const lines = [
    `# ${SITE_NAME} — Full site summary for AI systems`,
    "",
    AEO_DEFINITION,
    "",
    "## Metadata",
    `- Name: ${SITE_NAME}`,
    `- URL: ${SITE_URL}`,
    `- Description: ${SITE_DESCRIPTION}`,
    `- Tagline: ${SITE_TAGLINE}`,
    `- Launch: ${LAUNCH_DATE_LABEL}`,
    `- Email: ${ORGANIZATION.email}`,
    `- Parent: ${ORGANIZATION.parentOrganization.name} (${ORGANIZATION.parentOrganization.url})`,
    "",
    "## Keywords (discovery)",
    SITE_KEYWORDS.join(", "),
    "",
    "## Key facts",
    ...AEO_BULLETS.map((b) => `- ${b}`),
    "",
    "## Founders",
    ...ORGANIZATION.founders.map((f) => {
      const url = f.url ? ` (${f.url})` : "";
      return `- ${f.name}, ${f.role}${url}: ${f.description}`;
    }),
    "",
    "## Intro video",
    `- Title: ${INTRO_VIDEO.name}`,
    `- URL: ${INTRO_VIDEO.watchUrl}`,
    `- Description: ${INTRO_VIDEO.description}`,
    "",
    "## Launch features (" + LAUNCH_DATE_LABEL + ")",
    ...launchFeatures.map((f) => `- ${f.title} [${f.tag}]: ${f.desc}`),
    "",
    "## Program pillars",
    ...PROGRAM_PILLARS.map((p) => `- ${p.name}: ${p.description}`),
    "",
    "## Site sections",
    "- #about — What is Reborn Academy (AEO summary)",
    "- #launch — Launch features and coming-soon ecosystem",
    "- #timeline — Road to November 1, 2026",
    "- #journey — A day inside Reborn Academy",
    "- #programs — Faith, Fitness, Business, Finances, Family pillars",
    "- #academy — Platform preview (dashboard, app mock)",
    "- #affiliate — Built-in affiliate program",
    "- #giveaways — Launch giveaways and member rewards",
    "- #community — Live community, accountability, faith-first culture",
    "- #founders — Mike Gagat and Daniel Ziedins",
    "- #faq — Frequently asked questions (14 items)",
    "- #waitlist — Join waitlist for relaunch",
    "",
    "## Products at launch",
    "- Reborn Academy Member Dashboard (WebApplication)",
    "- Reborn Academy App (MobileApplication, iOS/Android)",
    "- RB Insiders premium tier",
    "- Built-in affiliate program",
    "- Launch giveaways and member rewards",
    "",
    "## FAQ (complete)",
    ...FAQ_ITEMS.flatMap((f) => [`### ${f.question}`, f.answer, ""]),
    "",
    "## Same as / official links",
    ORGANIZATION.sameAs.join("\n"),
    "",
    "## Machine-readable endpoints",
    `- ai.txt: ${SITE_URL}/ai.txt`,
    `- llms.txt: ${SITE_URL}/llms.txt`,
    `- sitemap: ${SITE_URL}/sitemap.xml`,
  ];

  return new Response(lines.join("\n"), {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=86400",
    },
  });
}
